# Generated by Django 6.0.3 on 2026-03-04 03:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedPatient',
            fields=[
                ('patient_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=6)),
                ('contact', models.CharField(max_length=11)),
                ('street', models.CharField(blank=True, max_length=50, null=True)),
                ('barangay', models.CharField(blank=True, max_length=3, null=True)),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('pin', models.CharField(max_length=255)),
                ('fingerprint_id', models.CharField(blank=True, max_length=4, null=True)),
                ('last_visit', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('original_created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Archived Patient',
                'db_table': 'archived_patient',
            },
        ),
        migrations.CreateModel(
            name='HCStaff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('staff_pin', models.CharField(max_length=255, unique=True)),
                ('phone', models.CharField(default='N/A', max_length=11)),
                ('email', models.EmailField(default='N/A', max_length=254)),
                ('position', models.CharField(default='N/A', max_length=50)),
                ('department', models.CharField(default='N/A', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('contact', models.CharField(default='N/A', max_length=11)),
                ('street', models.CharField(blank=True, max_length=50, null=True)),
                ('barangay', models.CharField(blank=True, max_length=3, null=True)),
                ('username', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('pin', models.CharField(max_length=255)),
                ('fingerprint_id', models.CharField(blank=True, max_length=4, null=True, unique=True)),
                ('last_visit', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArchivedQueueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_status', models.CharField(max_length=10)),
                ('entered_at', models.DateTimeField()),
                ('queue_number', models.CharField(max_length=10)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='api.archivedpatient')),
            ],
            options={
                'db_table': 'archived_queue_entry',
            },
        ),
        migrations.CreateModel(
            name='ArchivedVitalSigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_recorded', models.DateTimeField()),
                ('heart_rate', models.IntegerField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('oxygen_saturation', models.FloatField(blank=True, null=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=7, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='api.archivedpatient')),
            ],
            options={
                'db_table': 'archived_vital_signs',
            },
        ),
        migrations.CreateModel(
            name='QueueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_status', models.CharField(blank=True, choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('NORMAL', 'Normal')], max_length=10, null=True)),
                ('entered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('queue_number', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('SERVING', 'Currently Being Served'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='WAITING', max_length=10)),
                ('served_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='api.patient')),
            ],
            options={
                'ordering': ['-entered_at'],
            },
        ),
        migrations.CreateModel(
            name='VitalSigns',
            fields=[
                ('vitals_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time_recorded', models.DateTimeField(auto_now_add=True)),
                ('heart_rate', models.IntegerField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('oxygen_saturation', models.FloatField(blank=True, null=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=7, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='api.patient')),
            ],
        ),
    ]
