# Generated by Django 6.0.3 on 2026-03-04 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hcstaff',
            old_name='staff_pin',
            new_name='pin',
        ),
    ]
