# Generated by Django 6.0.4 on 2026-05-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='barangay',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
