# Generated by Django 5.2.7 on 2026-03-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_staff_pin_hcstaff_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='hcstaff',
            name='fingerprint_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
