# Generated by Django 6.0.2 on 2026-02-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_heart_rate_archivedvitalsigns_pulse_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vitalsigns',
            name='id',
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='vitals_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
