# Generated by Django 6.0.2 on 2026-02-24 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_vitalsigns_id_vitalsigns_vitals_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archivedvitalsigns',
            old_name='pulse_rate',
            new_name='heart_rate',
        ),
        migrations.RenameField(
            model_name='vitalsigns',
            old_name='pulse_rate',
            new_name='heart_rate',
        ),
    ]
