# Generated by Django 5.2.8 on 2025-11-12 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_middle_initial_archivedpatient_middle_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queueentry',
            old_name='priority',
            new_name='priority_status',
        ),
    ]
