# Generated by Django 5.2.8 on 2025-11-12 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_priority_queueentry_priority_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archivedqueueentry',
            old_name='priority',
            new_name='priority_status',
        ),
    ]
