# Generated by Django 5.2.8 on 2025-11-12 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_priority_archivedqueueentry_priority_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='fingerprint_template',
        ),
    ]
