# Generated by Django 5.2.8 on 2025-11-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_patient_address_patient_barangay_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivedpatient',
            name='address',
        ),
        migrations.AddField(
            model_name='archivedpatient',
            name='barangay',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='archivedpatient',
            name='street',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
