# Generated by Django 5.2.8 on 2025-11-12 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_archivedpatient_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivedpatient',
            name='fingerprint_template',
        ),
    ]
