# Generated by Django 5.2.8 on 2025-11-12 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_archivedpatient_fingerprint_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivedpatient',
            name='archive_reason',
        ),
        migrations.RemoveField(
            model_name='archivedpatient',
            name='archived_by',
        ),
    ]
