# Generated by Django 5.2.8 on 2025-11-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_archivedpatient_archive_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedvitalsigns',
            name='blood_pressure',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
